# Generated by Django 6.1 on 2026-09-20 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_testimonial_menu_category_alter_menu_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='category',
            field=models.CharField(choices=[('Starters', 'Starters'), ('Main Courses', 'Main Courses'), ('Desserts', 'Desserts'), ('Drinks', 'Drinks'), ('Uncategorized', 'Uncategorized')], default='Uncategorized', max_length=100),
        ),
    ]
